name: Ubuntu - Build new templates for all versions

on:
  workflow_dispatch:
    inputs:
      location:
         required: false
         type: choice
         options: 
           - hel1
           - fsn1
           - nbg1
         default: "hel1"
      servertype:
         required: false
         type: choice
         options: 
           - ccx13
         default: "ccx13"

  schedule:
    - cron: "30 09 * * 3"

    
env:
  # The packer init command queries GitHub's public API, which rate limits requests per IP address.
  # https://horrell.ca/setting-packer_github_api_token-when-running-packer-in-a-github-action/
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}

  # Custom variables
  location: ${{ github.event_name == 'schedule' && 'hel1' || github.event.inputs.location }}
  servertype: ${{ github.event_name == 'schedule' && 'ccx13' || github.event.inputs.servertype }}
  

jobs:
  Preparations:
    runs-on: ubuntu-latest

    steps:
      - name: Assign ENV variable to workflow variable
        id: env
        run: |
          echo "location=$location" >> $GITHUB_OUTPUT
          echo "servertype=$servertype" >> $GITHUB_OUTPUT

    outputs:      
     HCloudServerLocation: ${{ steps.env.outputs.location }}
     HCloudServerType: ${{ steps.env.outputs.servertype }}


  Job:
    needs: Preparations
    
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ['ubuntu20', 'ubuntu22', 'ubuntu24']

    uses: ./.github/workflows/ubuntu_build-new-template-for-specific-version.yml
    with:
      os: ${{ matrix.os }}
      location: ${{ needs.Preparations.outputs.HCloudServerLocation }}
      servertype: ${{ needs.Preparations.outputs.HCloudServerType }}
    secrets: inherit
